---
- name: Can connect to the Ansible Tower with the given username/password
  uri:
    url: "{{ tower_url }}/api/v2/ping/"
    user: "{{ tower_user }}"
    password: "{{ tower_password }}"
    force_basic_auth: true
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_uuid_json
