---
- name: Can connect to the Ansible Tower with the given username/password
  uri:
    url: "{{ tower_url }}/api/v2/ping/"
    user: "{{ tower_user }}"
    password: "{{ tower_password }}"
    force_basic_auth: true
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_uuid_json
- name: List all organizations in Tower using userid and password
  uri:
    url: "{{ tower_url }}/api/v2/organizations"
    user: "{{ tower_user }}"
    password: "{{ tower_password }}"
    return_content: yes
    validate_certs: "{{ tower_validate_certs }}"
    force_basic_auth: yes
  register: ansible_orgs_json
