---
- name: Can connect to the Ansible Tower with token
  uri:
    url: "{{ tower_url }}/api/v2/ping/"
    validate_certs: "{{ tower_validate_certs }}"
    headers:
      Authorization: "Bearer {{ tower_token }}"
  register: tower_uuid_json
