---
- name: Can connect to the Ansible Tower with token
  uri:
    url: "{{ tower_url }}/api/v2/ping/"
    validate_certs: "{{ tower_validate_certs }}"
    headers:
      Authorization: "Bearer {{ tower_token }}"
  register: tower_uuid_json
  when: tower_token | length > 0
- name: Can connect to the Ansible Tower with the given username/password
  uri:
    url: "{{ tower_url }}/api/v2/ping/"
    user: "{{ tower_user }}"
    password: "{{ tower_password }}"
    force_basic_auth: true
    validate_certs: "{{ tower_validate_certs }}"
  register: tower_uuid_json
  when: tower_token | length == 0
- name: List all organizations in Tower using token
  uri:
    url: "{{ tower_url }}/api/v2/organizations"
    return_content: yes
    validate_certs: "{{ tower_validate_certs }}"
    headers:
      Authorization: "Bearer {{ tower_token }}"
  register: ansible_orgs_json
  when: tower_token | length > 0
- name: List all organizations in Tower using userid and password
  uri:
    url: "{{ tower_url }}/api/v2/organizations"
    user: "{{ tower_user }}"
    password: "{{ tower_password }}"
    return_content: yes
    validate_certs: "{{ tower_validate_certs }}"
    force_basic_auth: yes
  register: ansible_orgs_json
  when: tower_token | length == 0
