---
- name: Extract Organization ID
  set_fact:
    tower_account_id: "{{ org_id|string }}"
- name: If an account number is findable
  block:
  - debug:
      msg: "Account {{ tower_account_id }} associated with organization {{ org_id }}"
  - name: "Make configuration directory for account {{ tower_account_id }}"
    file:
      path: "{{ receptor_config_dir }}/rh_ansible_{{ tower_account_id }}"
      state: directory
      mode: 0755
  - name: "Make a data directory for account {{ tower_account_id }}"
    file:
      path: "{{ receptor_data_dir }}/rh_ansible_{{ tower_account_id }}"
      state: directory
      mode: 0755
  - name: Generate a new UUID
    command:
      cmd: uuidgen
    register: uuid_output
  - name: Save UUID for this Receptor node
    copy:
      dest: "{{ receptor_config_dir }}/rh_ansible_{{ tower_account_id }}/uuid"
      content: |
        {{ uuid_output.stdout }}
    when: existing_receptor_node_id is not defined
  - name: Generate a UUID file from existing receptor_node_id
    copy:
      dest: "{{ receptor_config_dir }}/rh_ansible_{{ tower_account_id }}/uuid"
      content: |
        {{ existing_receptor_node_id }}
    when: existing_receptor_node_id is defined

  - name: "Write Receptor configuration for account {{ tower_account_id }} using token"
    template:
      dest: "{{ receptor_config_dir }}/rh_ansible_{{ tower_account_id }}/receptor.conf"
      mode: 0400
      src: receptor_token.conf.j2
    when: tower_token | length > 0
  - name: "Write Receptor configuration for account {{ tower_account_id }} using userid/password"
    template:
      dest: "{{ receptor_config_dir }}/rh_ansible_{{ tower_account_id }}/receptor.conf"
      mode: 0400
      src: receptor.conf.j2
    when: tower_token | length == 0
  when: tower_account_id | length > 0
