---
- name: "Check if we have package for RHEL{{ ansible_distribution_major_version }}"
  fail:
     msg: "Automation Service Catalog package not defined for RHEL{{ ansible_distribution_major_version }}"
  when: ansible_distribution_major_version not in asc_package_name.keys()
- name: "Get Pool Ids for SKU {{ rhsm_asc_sku }}"
  command: "subscription-manager list --available --matches={{ rhsm_asc_sku }} --pool-only"
  register: sub_cmd
  changed_when: False
- name: Attach Pool ID's
  command: "subscription-manager attach --pool {{ item }}"
  loop: "{{ sub_cmd.stdout_lines }}"
  changed_when: True
- name: "Enable the repository {{ asc_package_name[ansible_distribution_major_version] }}"
  command: "subscription-manager repos --enable {{ asc_package_name[ansible_distribution_major_version] }}"
  changed_when: True
