---
- name: Create Receptor Script
  block:
  - name: Generate shell script from template
    template:
      src: receptor.sh.j2
      dest: "{{ receptor_config_dir }}/{{ item }}/receptor.sh"
      mode: 0755
    loop: "{{ account_dirs }}"
  tags: install_local_scripts
